name: leafy_leasing
version: 1.0.0+1
publish_to: none
description: A companion app for PaaS (Plants as a Service) companies.
environment: 
  sdk: '>=3.0.0'
dependencies: 
  auto_route: ^7.1.0
  auto_size_text: ^3.0.0
  blobs: ^2.0.0
  dartx: ^1.1.0
  easy_debounce: ^2.0.3
  flash: ^3.0.3
  flutter_animate: ^4.2.0
  flutter_dotenv: ^5.0.2
  flutter_hooks: ^0.18.6
  freezed: ^2.1.0
  freezed_annotation: ^2.2.0
  gap: ^2.0.0
  google_fonts: ^4.0.4
  hive_flutter: any
  hive_generator: any
  hooks_riverpod: ^2.3.6
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.0
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.8.0
  logger: ^1.3.0
  overlay_support: ^2.1.0
  path_provider: ^2.0.14
  relative_time: ^3.0.0
  retry: ^3.1.1
  rive: ^0.11.2
  riverpod_annotation: ^2.1.1
  rnd: ^0.2.0
  settings_ui: ^2.0.2
  stash: ^5.0.0
#  stash_sembast_web: ^5.0.0
  visibility_detector: ^0.4.0+2

  stash_isar: ^5.0.0
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  isar: ^3.1.0+1
  animated_glitch: ^1.1.1
  animated_text_kit: ^4.2.2
dev_dependencies: 
  auto_route_generator: ^7.0.0
  build_runner: ^2.1.7
  custom_lint: any
  flutter_launcher_icons: ^0.13.1
  json_serializable: any
  mocktail: ^0.3.0
  pubspec_dependency_sorter: ^1.0.3
  riverpod_generator: ^2.2.1
  riverpod_lint: ^1.3.1
  very_good_analysis: ^3.1.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
flutter: 
  assets: 
    - assets/image/logo.png
    - assets/image/logo_v2.png
    - assets/mock_data/customers.json
    - assets/mock_data/appointments.json
    - assets/mock_data/appointment_metas.json
    - assets/flutter_rive.riv
    - assets/google_fonts/
    - dotenv/global.env
    - dotenv/dev.env
    - dotenv/production.env
    - dotenv/staging.env
  uses-material-design: true
  generate: true
