///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String dotenvDev = 'dotenv/dev.env';
  static const String dotenvGlobal = 'dotenv/global.env';
  static const String dotenvProduction = 'dotenv/production.env';
  static const String dotenvStaging = 'dotenv/staging.env';
  static const String imageLogo = 'assets/image/logo.png';
  static const String imageLogoV2 = 'assets/image/logo_v2.png';
  static const String mockDataAppointmentMetas =
      'assets/mock_data/appointment_metas.json';
  static const String mockDataAppointments =
      'assets/mock_data/appointments.json';
  static const String mockDataCustomers = 'assets/mock_data/customers.json';
}
