///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String assetsFlutterRive = 'assets/flutter_rive.riv';
  static const String assetsImageLogo = 'assets/image/logo.png';
  static const String assetsImageLogoV2 = 'assets/image/logo_v2.png';
  static const String assetsMockDataAppointmentMetas =
      'assets/mock_data/appointment_metas.json';
  static const String assetsMockDataAppointments =
      'assets/mock_data/appointments.json';
  static const String assetsMockDataCustomers =
      'assets/mock_data/customers.json';
  static const String dotenvDev = 'dotenv/dev.env';
  static const String dotenvGlobal = 'dotenv/global.env';
  static const String dotenvProduction = 'dotenv/production.env';
  static const String dotenvStaging = 'dotenv/staging.env';
  static const String felixHomepageAssetsFlutterRive =
      'assets/flutter_rive.riv';
  static const String googleFontsAbhayaLibreBold =
      'assets/google_fonts/AbhayaLibre-Bold.ttf';
  static const String googleFontsAbhayaLibreExtraBold =
      'assets/google_fonts/AbhayaLibre-ExtraBold.ttf';
  static const String googleFontsAbhayaLibreMedium =
      'assets/google_fonts/AbhayaLibre-Medium.ttf';
  static const String googleFontsAbhayaLibreRegular =
      'assets/google_fonts/AbhayaLibre-Regular.ttf';
  static const String googleFontsAbhayaLibreSemiBold =
      'assets/google_fonts/AbhayaLibre-SemiBold.ttf';
  static const String googleFontsOFL = 'assets/google_fonts/OFL.txt';
  static const String imageLogo = 'assets/image/logo.png';
  static const String imageLogoV2 = 'assets/image/logo_v2.png';
  static const String mockDataAppointmentMetas =
      'assets/mock_data/appointment_metas.json';
  static const String mockDataAppointments =
      'assets/mock_data/appointments.json';
  static const String mockDataCustomers = 'assets/mock_data/customers.json';
}
