name: leafy_leasing

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on: [push]
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main

env:
  SECRETS_FILE_CONTENTS: ${{ secrets.SECRETS_FILE_CONTENTS }}

jobs:
  semantic-pull-request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      setup : |
        echo $SECRETS_FILE_CONTENTS | base64 -d > lib/shared/secrets.dart
        echo $SECRETS_FILE_CONTENTS

#  spell-check:
#    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/spell_check.yml@v1
#    with:
#      includes: |
#        **/*.md
#      modified_files_only: false