name: leafy_leasing

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on: [push]
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main



jobs:
  semantic-pull-request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      env:
        MY_ENV_VAR: 'lol'
      flutter_channel: stable
      setup : echo "$MY_ENV_VAR"

#  spell-check:
#    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/spell_check.yml@v1
#    with:
#      includes: |
#        **/*.md
#      modified_files_only: false