#name: leafy_leasing

concurrency:
  group: $-$
  cancel-in-progress: true

on: [push]
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main

jobs:
# create a job that echos a GitHub secret

  semantic-pull-request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Secrets
        run: |
          echo $SECRETS_FILE_CONTENTS | base64 -d > lib/shared/secrets.dart
          echo $SECRETS_FILE_CONTENTS
        env:
          SECRETS_FILE_CONTENTS: ${{ secrets.SECRETS_FILE_CONTENTS }}

      - name: Very Good Stuff
        uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
        with:
          flutter_channel: stable

#  spell-check:
#    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/spell_check.yml@v1
#    with:
#      includes: |
#        **/*.md
#      modified_files_only: false